=== fedorovVNpin221/SPBcastles_website_xml/xml_piter-schema.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Piter (castle+)>
<!ELEMENT castle (id, insignia)>
<!ATTLIST castle
          name CDATA #REQUIRED>
<!ELEMENT id (#PCDATA)>
<!ELEMENT insignia (sign+)>
<!ELEMENT sign ((image) | (info))>
<!ELEMENT image EMPTY>
<!ATTLIST image
          src CDATA #REQUIRED>
<!ELEMENT info (#PCDATA)>

=== fedorovVNpin221/SPBcastles_website_xml/~xml_piter.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE Piter SYSTEM "C:\Users\slavk\Desktop\Новая папка\xml_piter-schema.dtd">

<Piter>
       <castle name="Зимний дворец">
       <id>1</id>
       <insignia>

       <sign>
       <image src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Зимний_дворец_Петра_I_-_фрагмент_Махаева.jpg/548px-Зимний_дворец_Петра_I_-_фрагмент_Махаева.jpg"/>
       </sign>

       <sign>
       <info>
       Автор проекта: Георг Маттарнови, Николай Гербель
       </info>
       </sign>

       <sign>
       <info>
       Зимний дворец Петра I — личная резиденция императора Петра I, возведённая на набережной Невы у Зимней канавки, архитектурный памятник начала XVIII века, частично сохранившийся и находящийся в здании Эрмитажного театра, включён в музейный комплекс Государственного Эрмитажа.Автор проекта: Георг Маттарнови, Николай Гербель
       </info>
       </sign>

       </insignia>
       </castle>

       <castle name="Елагин дворец">
       <id>2</id>
       <insignia>

       <sign>
       <image src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Spb_06-2012_Elagin_Palace.jpg/548px-Spb_06-2012_Elagin_Palace.jpg"/>
       </sign>

       <sign>
       <info>
       Архитектор: Д. Кваренги, К. Росси
       </info>
       </sign>

       <sign>
       <info>
       Елагин дворец — летний императорский дворец на Елагином острове в Санкт-Петербурге. Названный Елагиным по имени своего первого владельца, он так и сохранил это название, несмотря на периодическую смену хозяев. Дворец также называют Елагинским или Елагиноостровским.
       </info>
       </sign>

       </insignia>
       </castle>

       <castle name ="Дворец Петра II">
       <id>3</id>
       <insignia>

       <sign>
       <image src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Peter_II_Palace_in_SPB.jpg/548px-Peter_II_Palace_in_SPB.jpg"/>
       </sign>

       <sign>
       <info>
       Архитектор: Доменико Трезини
       </info>
       </sign>

       <sign>
       <info>
       Дворец Петра II — памятник архитектуры. Расположен в Санкт-Петербурге, современный адрес дома — Университетская набережная, 11, Филологический переулок.
       </info>
       </sign>

       </insignia>
       </castle>

       <castle name ="Каменноостровский дворец">
       <id>4</id>
       <insignia>

       <sign>
       <image src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Каменноостровский_дворец.jpg/548px-Каменноостровский_дворец.jpg"/>
       </sign>

       <sign>
       <info>
       Автор проекта: В. И Баженов
       </info>
       </sign>

       <sign>
       <info>
       Каменноостровский дворец — один из дворцов Санкт-Петербурга, памятник времён Екатерины II, загородная императорская резиденция. Памятник архитектуры федерального значения.
       </info>
       </sign>

       </insignia>
       </castle>

       <castle name ="Михайловский замок">
       <id>5</id>
       <insignia>

       <sign>
       <image src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/RUS-2016-Aerial-SPB-St_Michael%27s_Castle.jpg/548px-RUS-2016-Aerial-SPB-St_Michael%27s_Castle.jpg"/>
       </sign>

       <sign>
       <info>
       Архитектор: Винченцо Бренна и Василий Иванович Баженов
       </info>
       </sign>

       <sign>
       <info>
       Михайловский, или Инженерный, замок — бывший императорский дворец в центре Санкт-Петербурга по адресу Садовая ул., № 2. Возведён по заказу императора Павла I на рубеже XVIII—XIX веков в стиле романтического классицизма по типу «замка на воде» (расположен на стыке реки Мойки и реки Фонтанки; с западной и южной сторон были несохранившийся Церковный канал и ныне частично засыпанный Воскресенский канал). Вскоре по завершении строительства, 12 марта 1801 года, дворец стал местом его убийства. Общая сумма расходов на возведение и украшение замка составила 6 миллионов 171 тысячу 69 рублей[
       </info>
       </sign>

       </insignia>
       </castle>

       <castle name ="Таврический дворец">
       <id>6</id>
       <insignia>

       <sign>
       <image src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/RUS-2016-SPB-Tauride_Palace.jpg/600px-RUS-2016-SPB-Tauride_Palace.jpg"/>
       </sign>

       <sign>
       <info>
       Архитектор: Иван Старов
       </info>
       </sign>

       <sign>
       <info>
       Таврический дворец — петербургская резиденция князя Григория Потёмкина-Таврического. Возведён в стиле классицизма в период с 1783 по 1789 год по проекту архитектора И. Е. Старова.
       </info>
       </sign>

       </insignia>
       </castle>

       <castle name ="Чесменский дворец">
       <id>7</id>
       <insignia>

       <sign>
       <image src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Chesma_Palace10.jpg/1920px-Chesma_Palace10.jpg"/>
       </sign>

       <sign>
       <info>
       Архитектор: Юрий Матвеевич Фельтен
       </info>
       </sign>

       <sign>
       <info>
       Чесменский дворец — императорский путевой дворец, расположенный в Санкт-Петербурге. Был возведён по проекту архитектора Ю. М. Фельтена по заказу императрицы Екатерины Второй в стиле псевдоготики. Памятник архитектуры. Вместе с Чесменской церковью составлял некогда уникальный ансамбль, обращённый к бывшему Царскосельскому тракту.
       </info>
       </sign>

       </insignia>
       </castle>

       <castle name ="Большой дворец">
       <id>8</id>
       <insignia>

       <sign>
       <image src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Большой_дворец_-_2.jpg/548px-Большой_дворец_-_2.jpg"/>
       </sign>

       <sign>
       <info>
       Архитектор: Франческо Растрелли
       </info>
       </sign>

       <sign>
       <info>
       Большой дворец — основное здание дворцово-паркового ансамбля «Петергоф», расположенного в одноимённом городе на южном берегу Финского залива в Петродворцовом районе города федерального значения Санкт-Петербурга. Был практически полностью разрушен во время Второй мировой войны, в 1952 году восстановлен.
       </info>
       </sign>

       </insignia>
       </castle>

       <castle name ="Большой Гатчинский дворец">
       <id>9</id>
       <insignia>

       <sign>
       <image src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Gatchina_Palace%2C_Southern_facade.jpg/548px-Gatchina_Palace%2C_Southern_facade.jpg"/>
       </sign>

       <sign>
       <info>
       Архитектор: Антонио Ринальди
       </info>
       </sign>

       <sign>
       <info>
       Большой Гатчинский дворец был построен в 1766—1781 годах в Гатчине по проекту итальянского архитектора Антонио Ринальди в стиле классицизма для фаворита Екатерины II графа Григория Григорьевича Орлова. Расположенный на холме над Серебряным озером дворец сочетает в себе темы средневекового за́мка и загородной резиденции. Интерьеры дворца — образец русского классицизма рубежа XVIII—XIX веков. Дворец был одним из любимых мест отдыха царской семьи.
       </info>
       </sign>

       </insignia>
       </castle>

       <castle name ="Запасной дворец">
       <id>10</id>
       <insignia>

       <sign>
       <image src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/092._Пушкин._Садовая_ул._22._Дача_Кочубей_М.В..JPG/548px-092._Пушкин._Садовая_ул._22._Дача_Кочубей_М.В..JPG"/>
       </sign>

       <sign>
       <info>
       Строитель: Адам Менелас
       </info>
       </sign>

       <sign>
       <info>
       Запасной дворец (дача Кочубея), Владимирский дворец, Дача Кочубей М. В., Запасный дворец — дворец в городе Пушкине. Расположен на Садовой улице, 22 (Софийский бульв., 2, 4, 6, 8, 10), на берегу 4-го Нижнего пруда. С 2010 года во дворце располагается дворец бракосочетания № 3
       </info>
       </sign>

       </insignia>
       </castle>

       <castle name ="Константиновский дворец">
       <id>11</id>
       <insignia>

       <sign>
       <image src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Константиновский.jpg/548px-Константиновский.jpg"/>
       </sign>

       <sign>
       <info>
       Архитектор: Жан-Батист Леблон
       </info>
       </sign>

       <sign>
       <info>
       Константиновский дворец (Большой Стрельнинский дворец) — памятник архитектуры XVIII века, формирующий дворцово-парковый ансамбль в Стрельне, с 2003 года — Государственный комплекс «Дворец конгрессов». Комплекс находится на южном берегу Финского залива на реках Стрелка и Кикенка вдоль Петергофской дороги в 19 км от центра Санкт-Петербурга.
       </info>
       </sign>

       </insignia>
       </castle>

       <castle name ="Петергоф">
       <id>12</id>
       <insignia>

       <sign>
       <image src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/RUS-2016-Aerial-SPB-Peterhof_Palace.jpg/600px-RUS-2016-Aerial-SPB-Peterhof_Palace.jpg"/>
       </sign>

       <sign>
       <info>
       Архитектор: Жан-Батист Леблон
       </info>
       </sign>

       <sign>
       <info>
       Петергоф (от нем. Péterhof — «двор Петера») — дворцово-парковый ансамбль на южном берегу Финского залива. Находится на территории муниципального образования город Петергоф (с 1944 года по 1997 год[1] — «Петродворец») в Петродворцовом районе Санкт-Петербурга. От него произошло название «Петергофской дороги». Часть его находится в ведении государственного музея-заповедника «Петергоф».
       </info>
       </sign>

       </insignia>
       </castle>

</Piter>
